name: Cache purge

permissions:
  contents: read

on: workflow_dispatch

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  purge-cloudflare-cache:
    runs-on: ubuntu-latest
    steps:
      - name: Purge all Cloudflare cache
        env:
          ZONE_ID: ${{ secrets.CLOUDFLARE_ZONE_ID }}
          EMAIL: ${{ secrets.EMAIL_GUI }}
          AUTH_TOKEN: ${{ secrets.CLOUDFLARE_PURGE_CACHE }}
        run: |
          curl -X POST "https://api.cloudflare.com/client/v4/zones/${ZONE_ID}/purge_cache" -H "X-Auth-Email: ${EMAIL}" -H "Authorization: Bearer ${AUTH_TOKEN}" -H "Content-Type: application/json" --data '{"purge_everything": true}'
