name: Code minification
description: Minify code and push for deployment to GitHub Pages

on:
  workflow_dispatch:
  push:
    branches: [live]

jobs:
  minify-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@main
        with:
          fetch-depth: 0

      - name: Install NodeJS
        uses: actions/setup-node@main
        with:
          node-version: 22
      
      - name: Install CLI tools
        run: |
          npm install -g html-minifier
          npm install -g lightningcss-cli
          npm install -g terser
          npm install @sentry/cli

      - name: Minify HTML with HTMLMinifier
        continue-on-error: true
        run: |
          find . -name "*.html" -exec html-minifier {} -o {} --collapse-whitespace --remove-comments --remove-redundant-attributes --remove-script-type-attributes --use-short-doctype --collapse-boolean-attributes --remove-empty-attributes --remove-style-link-type-attributes --minify-css --minify-js \;
          
      - name: Minify CSS with Lightning CSS
        continue-on-error: true
        run: |
          find . -name "*.css" -exec lightningcss -m {} -o {} \;
          
      - name: Minify JavaScript with Terser
        continue-on-error: true
        run: |
          find . -name "*.js" -exec terser {} -o {} --compress --mangle --source-map \;

      - name: Upload source maps to Sentry
        uses: getsentry/action-release@v3
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: guiruggiero
          SENTRY_PROJECT: website
        with:
          sourcemaps: ./modules

      - name: Push changes to "live-min" branch
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add --all
          git commit -m "Automated minification and deployment of ${{ github.sha }}"
          git push --force -u origin live:live-min

      - name: Purge Cloudflare cache for HTML/CSS/JavaScript only
        run: |
          curl -X POST "https://api.cloudflare.com/client/v4/zones/695e9b8ac40b9d3c7274284cd5f4650f/purge_cache" -H "X-Auth-Email: ${{ SECRETS.EMAIL_GUI }}" -H "Authorization: Bearer ${{ SECRETS.CLOUDFLARE_PURGE_CACHE }}" -H "Content-Type: application/json" --data '{"files": ["https://guiruggiero.com/*.html", "https://guiruggiero.com/styles/*", "https://guiruggiero.com/modules/*"]}'
