name: Purge Cloudflare cache

on: workflow_dispatch

jobs:
  purge-cloudflare-cache:
    runs-on: ubuntu-latest
    steps:
      - run: |
          curl -X POST "https://api.cloudflare.com/client/v4/zones/695e9b8ac40b9d3c7274284cd5f4650f/purge_cache" -H "X-Auth-Email: ${{ SECRETS.EMAIL_GUI }}" -H "Authorization: Bearer ${{ SECRETS.CLOUDFLARE_PURGE_CACHE }}" -H "Content-Type: application/json" --data '{"purge_everything": true}'
